# Generated by Django 3.0.8 on 2020-08-04 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid')], max_length=150)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('shipment_total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cart.Cart')),
            ],
        ),
    ]
